apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo-pod
  ports:
    - protocol: TCP
      nodePort: 32585
      port: 3000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-pod
  template:
    metadata:
      labels:
        app: todo-pod
    spec:
      containers:
        - name: todo
          image: santhoshnath/todo:latest
          ports:
            - containerPort: 80
