name: Build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "infra/**"
      - ".github/**.yml"
      - "!.github/workflows/build.yml"
      - "**.md"
      - ".gitignore"

concurrency: ${{ github.workflow }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: echo ${{ github.token }} | docker login ghcr.io -u SanthoshNath --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/santhoshnath/todo .

      - name: Publish Docker image
        run: docker push ghcr.io/santhoshnath/todo

      - name: Post Build
        if: ${{ always() }}
        run: docker rmi ghcr.io/santhoshnath/todo
