name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "infra/**"
      - ".github/**.yml"
      - "!.github/workflows/build.yml"
      - "**.md"
      - ".gitignore"
      - ".pre-commit-config.yaml"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "infra/**"
      - ".github/**.yml"
      - "!.github/workflows/build.yml"
      - "**.md"
      - ".gitignore"
      - ".pre-commit-config.yaml"

concurrency: build_${{ github.ref }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        id: image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: ghcr.io/santhoshnath/todo
          cache-to: type=gha,ignore-error=true
          cache-from: type=gha
