name: Build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "infra/**"
      - ".github/**.yml"
      - "!.github/workflows/build.yml"
      - "**.md"
      - ".gitignore"

concurrency: ${{ github.workflow }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        id: image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/santhoshnath/todo
