name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - "master"

concurrency: ${{ github.workflow }}

jobs:
  Plan:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      max-parallel: 1
      matrix:
        environment: [ devl, prod ]

    steps:
      - uses: actions/checkout@v3

      - uses: SanthoshNath/setup-terragrunt@v2

      - name: Terragrunt plan
        working-directory: infra/${{ matrix.environment }}
        run: terragrunt run-all plan --terragrunt-non-interactive

  Apply:
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    needs: Plan
    strategy:
      max-parallel: 1
      matrix:
        environment: [ devl, prod ]
    if: false

    steps:
      - uses: actions/checkout@v3

      - uses: SanthoshNath/setup-terragrunt@v2

      - name: Docker login
        run: echo ${{ github.token }} | docker login ghcr.io -u SanthoshNath --password-stdin

      - name: Terragrunt plan
        working-directory: infra/${{ matrix.environment }}
        run: terragrunt run-all apply --terragrunt-non-interactive
