name: Docker

on:
  push:
    branches: [ 'master' ]
    paths-ignore: [ 'infra/**' ]
  pull_request:
    branches: [ 'master' ]
    paths-ignore: [ 'infra/**' ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag santhoshnath/todo

    - name: Docker login
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo "$password" | docker login --username "$username" --password-stdin
      
    - name: Publish Docker image
      run: docker push santhoshnath/todo
      
    - name: Cleanup
      run: |
        docker rmi santhoshnath/todo
        docker logout
