name: Docker

on:
  push:
    branches: [ 'master' ]
    paths-ignore: [ 'infra/**', '.github/workflows/terraform.yml', 'README.md' ]
  pull_request:
    types: [ opened, edited, closed, reopened ]
    branches: [ 'master' ]
    paths-ignore: [ 'infra/**', '.github/workflows/terraform.yml', 'README.md' ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag santhoshnath/todo

      - name: Docker login
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "$password" | docker login --username "$username" --password-stdin

      - name: Publish Docker image
        run: docker push santhoshnath/todo

      - name: Post Build
        if: ${{ always() }}
        run: |
          docker rmi santhoshnath/todo
          docker logout
