name: Terraform

on:
  push:
    branches: [ "master" ]
    paths: [ 'infra/**', '.github/workflows/terraform.yml', '!README.md' ]
  pull_request:
    branches: [ "master" ]
    paths: [ 'infra/**', '.github/workflows/terraform.yml', '!README.md' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  DEVL:
    runs-on: ubuntu-latest
    environment: DEVL
    if: inputs.environment == 'DEVL'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install terragrunt

      - name: Terraform plan
        working-directory: ./infra/devl
        run: terragrunt run-all plan --terragrunt-non-interactive

  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    if: inputs.environment == 'PROD'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install terragrunt

      - name: Terraform plan
        working-directory: ./infra/prod
        run: terragrunt run-all plan --terragrunt-non-interactive
