name: Terraform

on:
  push:
    branches: [ "master" ]
    paths: [ 'infra/**' ]
  pull_request:
    branches: [ "master" ]
    paths: [ 'infra/**' ]

jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install terragrunt

      - name: Terraform plan
        working-directory: ./infra/dev
        run: terragrunt run-all plan --terragrunt-non-interactive
