name: Terraform

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/terragrunt.yml"

concurrency: ${{ github.workflow }}

jobs:
  Plan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment: [ devl, prod ]

    steps:
      - uses: actions/checkout@v3

      - uses: SanthoshNath/setup-terragrunt@v2

      - name: Terraform plan
        working-directory: infra/${{ matrix.environment }}
        run: terragrunt run-all plan --terragrunt-non-interactive

  Apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: Plan
    strategy:
      max-parallel: 1
      matrix:
        environment: [ devl, prod ]
    if: false

    steps:
      - uses: actions/checkout@v3

      - uses: SanthoshNath/setup-terragrunt@v2

      - name: Terraform plan
        working-directory: infra/${{ matrix.environment }}
        run: terragrunt run-all apply --terragrunt-non-interactive
