name: Terraform

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true

concurrency: ${{ github.workflow }}

jobs:
  Plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: SanthoshNath/setup-terragrunt@v1

      - name: Terraform plan
        working-directory: ${{ github.event_name == 'workflow_dispatch' && format('infra/{0}', inputs.environment) || 'infra/devl' }}
        run: terragrunt run-all plan --terragrunt-non-interactive

  Apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: Plan
    if: false

    steps:
      - uses: actions/checkout@v3

      - uses: SanthoshNath/setup-terragrunt@v1

      - name: Terraform plan
        working-directory: ${{ github.event_name == 'workflow_dispatch' && format('infra/{0}', inputs.environment) || 'infra/devl' }}
        run: terragrunt run-all apply --terragrunt-non-interactive
