name: Todo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag santhoshnath/todo
      
  Publish:

    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo "$password" | docker login --username "$username" --password-stdin
      
    - name: Push Docker image
      run: docker push santhoshnath/todo
      
    - name: Cleanup
      run: |
        docker rmi santhoshnath/todo
        docker logout
