name: Todo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag santhoshnath/todo

    - name: Docker login
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo "$password" | docker login --username "$username" --password-stdin
      
    - name: Publish Docker image
      run: docker push santhoshnath/todo
      
    - name: Cleanup
      run: |
        docker rmi santhoshnath/todo
        docker logout
        
  Plan:

    runs-on: ubuntu-latest
    needs: Build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: brew install terragrunt
    
    - name: Terraform plan
      working-directory: ./infra/dev
      run: terragrunt run-all plan --terragrunt-non-interactive
